USE [master]
GO

/****** Object:  Database [E_Appartment]    Script Date: 1/16/2023 11:17:43 AM ******/
DROP DATABASE [E_Appartment]
GO

/****** Object:  Database [E_Appartment]    Script Date: 1/16/2023 11:17:43 AM ******/
CREATE DATABASE [E_Appartment]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'E_Appartment', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\E_Appartment.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'E_Appartment_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\E_Appartment_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [E_Appartment].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [E_Appartment] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [E_Appartment] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [E_Appartment] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [E_Appartment] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [E_Appartment] SET ARITHABORT OFF 
GO

ALTER DATABASE [E_Appartment] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [E_Appartment] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [E_Appartment] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [E_Appartment] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [E_Appartment] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [E_Appartment] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [E_Appartment] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [E_Appartment] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [E_Appartment] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [E_Appartment] SET  DISABLE_BROKER 
GO

ALTER DATABASE [E_Appartment] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [E_Appartment] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [E_Appartment] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [E_Appartment] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [E_Appartment] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [E_Appartment] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [E_Appartment] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [E_Appartment] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [E_Appartment] SET  MULTI_USER 
GO

ALTER DATABASE [E_Appartment] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [E_Appartment] SET DB_CHAINING OFF 
GO

ALTER DATABASE [E_Appartment] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [E_Appartment] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [E_Appartment] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [E_Appartment] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [E_Appartment] SET QUERY_STORE = ON
GO

ALTER DATABASE [E_Appartment] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [E_Appartment] SET  READ_WRITE 
GO


